meta_product_name: "Battle Monster"
meta_title: "Battle Monster - Product tagline"
meta_description: "Gagne tes combats avec tes monstres!"
meta_image: "https://onepage.dropagence.fr/game/bm/img/og-img.png"  should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
# https://onepage.dropagence.fr/game/bm/img/og-img.png
